### ISSUE TITLE
how to make our own fasta kmer file

### ISSUE THREAD

**Issue by sunhaifeng123** [OpenGene/fastv#1]
Hi

The fastv is so convenient and nice to use for the provided test data. But I'm curious about how to make our own kmer file if we use customized virus fasta.
Thanks in adcvance for your reply

Haifeng Sun
Nanjing Medical University

**Comment by sfchen** [comment]
I will make a guideline for that.

**Comment by sfchen** [comment]
You can download KMER file and Genome file of viruses from http://opengene.org/uniquekmer/virus/index.html. This is generated by extracting unique KMERs for all genomes in a big FASTA (http://opengene.org/viral.genomic.fasta), which contains all NCBI complete RefSeq release of viral sequences that can be found from https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/.

If you want to generate your own unique KMER files, please use UniqueKMER: https://github.com/OpenGene/UniqueKMER
