### ISSUE TITLE
detect large genome

### ISSUE THREAD

**Issue by rocpengliu** [OpenGene/fastv#2]
Hi, Shifu
Fastv is a fantastic tool.
I am wondering if fastv can detect large genome, such as bacteria, which have several MBs genome size? Or it has limitations of genome size.
Thank you so much!

**Comment by sfchen** [comment]
fastv supports genome size up to 16M

**Comment by wangshun1121** [comment]
Perhaps we can use Kmer file rather than genome file to detect reads from large genome: just detect specified Kmers

**Comment by rocpengliu** [comment]
Hi, Shifu
It's better to use kmer instead of raw genome sequence for the larger genomes.
looking forward to hearing the updates.
Thank you.

**Comment by KimBioInfoStudio** [comment]
When use a kmer file for detection, how to decide the k of the mer for PE150 NGS data

**Comment by sfchen** [comment]
> When use a kmer file for detection, how to decide the k of the mer for PE150 NGS data

default setting works well
