### ISSUE TITLE
clarify relationship to fastp

### ISSUE THREAD

**Issue by antonkulaga** [OpenGene/fastv#3]
Should I run fastv after fastp or fastv is just a fastp + additional features?

**Comment by sfchen** [comment]
Yes, you can run fastv with the data output by fastp.

Actually fastv will do the quality filtering as fastp  does. So you can input the raw data, but you can also input the clean data since the second time quality filtering will has no effect.

**Comment by antonkulaga** [comment]
@sfchen do I get it right is that fastv is like a new version of fastp with an additional feature of detecting contamination?

**Comment by sfchen** [comment]
> @sfchen do I get it right is that fastv is like a new version of fastp with an additional feature of detecting contamination?

No. fastv is only for detecting and visualizing viral sequences
