### ISSUE TITLE
Genome Coverages (click to show/hide)

### ISSUE THREAD

**Issue by yangzuokun** [OpenGene/fastv#5]
Genome Coverages (click to show/hide) showed nothing
![image](https://user-images.githubusercontent.com/33180540/82110264-59160200-976f-11ea-8fc8-d5463325bbff.png)

**Comment by sfchen** [comment]
Can you let me know what the browser you use?

And what's your command?

**Comment by yangzuokun** [comment]
fastv -i 1_clean_R1.fq.gz -I 1_clean_R2.fq.gz -g total.fa -h
 1.html -w 4

**Comment by sfchen** [comment]
Can you upload the HTML file here?

**Comment by yangzuokun** [comment]
[1.zip](https://github.com/OpenGene/fastv/files/4639623/1.zip

**Comment by sfchen** [comment]
Seems that the problem was due to incorrect `total.fa`

Can you upload it this total.fa here?

**Comment by yangzuokun** [comment]
![image](https://user-images.githubusercontent.com/33180540/82742535-2e8d0000-9d92-11ea-8c8f-df9db0aca331.png)
The virus genome is Unpublished， but .I checked the  fastv.json file, it is ok.

**Comment by sfchen** [comment]
I understand. But the problem is due to the format of the `total.fa`.

Can you give me a screenshot?

**Comment by sfchen** [comment]
Or you can send me an email so that it will not be public here.

chen@haplox.com

**Comment by yangzuokun** [comment]
![image](https://user-images.githubusercontent.com/33180540/82742630-40bb6e00-9d93-11ea-826a-ac06f7ef9663.png)

**Comment by sfchen** [comment]
Seems it is due to `CR`, `LF`.

Is this file generated in a Windows system?

**Comment by sfchen** [comment]
Just submitted a commit to fix this \r\n issue.
