### ISSUE TITLE
does fastv support batch run? 

### ISSUE THREAD

**Issue by mabouelk** [OpenGene/fastv#6]

**Comment by sfchen** [comment]
Batch run? Did you mean process many files at once?

**Comment by mabouelk** [comment]
yes

**Comment by sfchen** [comment]
No, it doesn't.

But this can be done with very simple scripts.

**Comment by mabouelk** [comment]
how? please can you help me with this?

**Comment by mabouelk** [comment]
I really appreciate your help, if I have multiple files, can you tell me how I can run fastv on them?
