### ISSUE TITLE
No high coverage kmer found 

### ISSUE THREAD

**Issue by mabouelk** [OpenGene/fastv#7]
the program was working well but today I reinstalled on a different machine and whenever I run it on fastq samples, I got this "NO high coverage Kmer found"

previously on the same samples, the program was giving positive results

**Comment by sfchen** [comment]
Can you please give me your command.

And please also submit the HTML result if applicable.

**Comment by mabouelk** [comment]
./fastv -i ncbi/public/sra/SRR11092056.fastq -g SARS-CoV-2.genomes.fa -c SARS-CoV-2.kmer.fa
[fastv report at 2020-05-22 22:25:00.pdf](https://github.com/OpenGene/fastv/files/4671189/fastv.report.at.2020-05-22.22.25.00.pdf)

**Comment by sfchen** [comment]
You used wrong command, please use:
```shell
./fastv -i ncbi/public/sra/SRR11092056.fastq -g SARS-CoV-2.genomes.fa -k SARS-CoV-2.kmer.fa
```

The option `-c` is for kmer collection file.

**Comment by mabouelk** [comment]
I am so sorry, I replaced the kmer with kmer collection. 
ok, regarding screening for all viruses, can you tell me which file is kmer and which is genome?

You can download k-mer files and genomes files of viruses from http://opengene.org/uniquekmer/viral/index.html. This is generated by extracting unique k-mers for all genomes in a big FASTA (http://opengene.org/viral.genomic.fasta), which contains all NCBI complete RefSeq release of viral sequences that can be found from https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/. 

regarding the last link is not loading

**Comment by sfchen** [comment]
1, download the k-mer collection file for all viruses in RefSeq: http://opengene.org/viral.kc.fasta.gz
2, use following command:
```shell
./fastv -i your.fq.gz -k viral.kc.fasta.gz
```

**Comment by sfchen** [comment]
If you want to pay particular attention to SARS-CoV-2 while scanning for all viruses, use:

```shell
./fastv -i your.fq.gz -c viral.kc.fasta.gz -g SARS-CoV-2.genomes.fa -k SARS-CoV-2.kmer.fa
```

**Comment by mabouelk** [comment]
Awesome!, what is the difference between both commands in term of output and speed?



________________________________

**Comment by mabouelk** [comment]
so I run the first command and I got the same message "no high coverage" and sequence and quality have different length!
and then in the HTML, I found a list of viruses, phage and bacteria even I screened it for viruses only. 

So my question, should I neglect the message "no high coverage and sequence length " and what is the cutoff for considering these hits(viruses, phage and bacteria)? 

[fastv report at 2020-05-23 00_46_19.pdf](https://github.com/OpenGene/fastv/files/4671214/fastv.report.at.2020-05-23.00_46_19.pdf)

**Comment by sfchen** [comment]
It depends.

Normally viruses with 90%+ coverage are with high confidence. So in your case, the sample was with SARS-CoV-2 and Influenza A

**Comment by mabouelk** [comment]
great, thank you so much

**Comment by sfchen** [comment]
> Awesome!, what is the difference between both commands in term of output and speed?
> […](#)

1, Output: the longer command provides two more sections: SARS-CoV-2 detection and SRS-CoV-2 genome coverage. The rest parts are same.
2, Speed: the longer command is a little slower, but still very fast.

**Comment by mabouelk** [comment]
I tried different ways to make it run of multiple input files at a time but I could not, Can you guide me how to do that?

**Comment by sfchen** [comment]
Use shell to do this. I cannot write the code for you since I don't have enough bandwidth. But it's not difficult.

**Comment by mabouelk** [comment]
Got it!, I figured it out. I am using it now with a good code on multiple files.

Thank you so much

**Comment by mabouelk** [comment]
Hi Dr. Chen, 


Please can you check your e-mail?
